# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

	config.vm.define "chzabakhS" do |s|
 		s.vm.provider "virtualbox" do |vb|
			vb.name = "chzabakhS"
 			vb.memory = 2048
			vb.cpus = 2
		end
	s.vm.box = "centos/8"
	s.vm.hostname = "chzabakhS"
	s.vm.network :private_network, ip: "192.168.42.110"
	s.vm.provision "shell", inline: <<-SHELL
	curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --flannel-iface=eth1
	SHELL
	s.vm.provision :shell, path: "./scripts/script.sh"
	end
end
