# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

	config.vm.define "chzabakhS" do |s|
 		s.vm.provider "virtualbox" do |vb|
			vb.name = "chzabakhS"
 			vb.memory = 1024
			vb.cpus = 1
		end
	s.vm.box = "centos/8"
	s.vm.hostname = "chzabakhS"
	s.vm.network :private_network, ip: "192.168.42.110"
	s.vm.provision "shell", inline: <<-SHELL
	curl -sfL https://get.k3s.io | sh -s - --no-deploy traefik --write-kubeconfig-mode 644 --node-name chzabakhS --flannel-iface=eth1
	sudo cat /var/lib/rancher/k3s/server/token > /home/vagrant/token
	SHELL
	end
	config.trigger.after :up do |trigger|
    	trigger.run = {inline: "vagrant scp chzabakhS:/home/vagrant/token ."}        #      vagrant plugin install vagrant-scp
	end
 	config.vm.define "chzabakhSW" do |sw|
 		sw.vm.provider "virtualbox" do |vb|
 			vb.memory = 1024
			vb.cpus = 1
			vb.name = "chzabakhSW"
 		end
    	sw.vm.box = "centos/8"
		sw.vm.hostname = "chzabakhSW"
		sw.vm.network :private_network, ip: "192.168.42.111"
		sw.vm.provision "shell", inline: <<-SHELL
		curl -sfL https://get.k3s.io | K3S_NODE_NAME=chzabakhSW K3S_URL=https://192.168.42.110:6443 K3S_TOKEN_FILE=/vagrant/token sh -s - --flannel-iface=eth1
		SHELL
	end

end
